name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Clean node_modules and package-lock
      run: rm -rf node_modules package-lock.json
    - name: Install dependencies
      run: npm install
    - name: Lint project
      run: npm run lint --if-present
    - name: Build project
      run: npm run build --if-present
    - name: Run tests
      run: npm test --if-present
